CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');

ALTER TABLE "User"
ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "User"
ALTER COLUMN "role" TYPE "UserRole"
USING "role"::"UserRole";

ALTER TABLE "User"
ALTER COLUMN "role" SET DEFAULT 'USER';